line-length = 100

[lint]
select = ["F", "E", "I", "B"]
ignore = [
    "F405",
    "F403",
    "E402",
    "F401",
    "E722",
    "E701",
    "F841",
    "E501",
    "B007",
    "B027",
    "B024",
    "E101",
]